//! Tauri's one command table, moved off `lib.rs` so an island can still be
//! registered (vingilot/docs/plans/2026-08-13-home-harbor.md, Task 3).
//!
//! **This file exists because of the repository's line ratchet, and the ratchet
//! was right.** `desktop/src-tauri/src/lib.rs` stood at exactly 1000 counted
//! lines of a 1000-line limit, and the seam entry for that file had already
//! written down what was going to happen: *"it is the one Tauri gives an app
//! for its command table and its run loop, every fork command costs it a line,
//! and at 999 of the repository ratchet's 1000 the next island to need one had
//! nowhere to put it… The house rule is split, never raise; this is the
//! split."* `vingilot_harbor` is that next island — five commands — and there
//! was not one line for them.
//!
//! **What moved is the list and nothing else.** The entries below are the same
//! entries, in the same order, that `lib.rs` carried; `lib.rs` now spends one
//! line on `.invoke_handler(vingilot_command_table::table!())`. No command was
//! renamed, none was added or removed in the move, and — the part that
//! decided the shape — **no command gained a prefix**. A `tauri::plugin` would
//! also have registered an island's commands, and `native_websocket.rs` shows
//! that pattern working in this very crate, but a plugin's commands are invoked
//! as `plugin:<name>|<command>`: adopting it for the fork's existing islands
//! would have rewritten every `invoke(…)` call site in the webview, and
//! adopting it for the harbor alone would still have cost `lib.rs` the one line
//! it did not have. Moving the table costs zero call sites and buys ~300 lines
//! of headroom for every island after this one.
//!
//! **The cost, stated plainly:** upstream adds commands to this list, in
//! `lib.rs`, on its own schedule, so an upstream merge that touches the table
//! will conflict here — a deletion on their side of the hunk against a file
//! that no longer holds it. The resolution is always the same and always
//! mechanical: their new entries go in this list. That is a conflict the seam
//! registry names in advance (`vingilot/seams/home-harbor.yaml`) rather than a
//! surprise, and it is the price the ratchet asks in exchange for a `lib.rs`
//! that a human can still read.
//!
//! **There are no imports in this file, and there must not be any.** See
//! [`table`] for why the list is a `macro_rules!` expanded at `lib.rs` rather
//! than a function called from it: every name in it resolves in the crate root's
//! scope, using `lib.rs`'s own `use commands::*;` and the rest, exactly as it
//! did before the move. A `use` added here would resolve nothing and shadow
//! nothing — it would just be dead.

/// Every command the webview may invoke.
///
/// **A `macro_rules!` rather than a function, and that is the whole trick.**
/// `#[tauri::command]` generates two hidden macros beside each function
/// (`__cmd__<name>` and `__tauri_command_name_<name>`), and it is those, not the
/// functions, that `generate_handler!` expands to. Some of them are unreachable
/// from here: the modules that define them are private (`mod personas;`,
/// `mod workspace;`) and re-export their commands by name, which carries the
/// function and leaves the macros behind a wall no `use` in this file can reach.
/// A `fn handler()` in this module therefore cannot be written at all — it fails
/// on thirteen of the 317 entries, and the fixes for that are all worse than
/// this: widening five upstream modules to `pub(crate)`, or naming private
/// module paths in the table.
///
/// Expanding at the call site sidesteps the wall entirely. `lib.rs` invokes this
/// where it used to write the list, so every name resolves in exactly the scope
/// that resolved it before — the crate root, with `lib.rs`'s own imports — and
/// the table needs no imports of its own. That is also why `lib.rs` keeps its
/// `use commands::*;` and the rest: they are what this expansion reads.
macro_rules! table {
    () => {
        tauri::generate_handler![
            take_pending_community_deep_link,
            acknowledge_pending_community_deep_link,
            start_builderlab_login,
            cancel_builderlab_login,
            get_builderlab_auth,
            clear_builderlab_auth,
            get_builderlab_nostr_identity,
            bind_builderlab_nostr_identity,
            delete_builderlab_nostr_identity,
            list_builderlab_communities,
            check_builderlab_community_name,
            create_builderlab_community,
            archive_builderlab_community,
            unarchive_builderlab_community,
            transfer_builderlab_community,
            title_bar_double_click,
            get_identity,
            get_nsec,
            generate_backup_passphrase,
            create_ncryptsec_backup,
            verify_ncryptsec_backup,
            save_ncryptsec_copy,
            import_identity,
            persist_current_identity,
            get_profile,
            update_profile,
            update_profile_at_relay,
            get_user_profile,
            get_users_batch,
            get_user_notes,
            get_git_identity,
            get_project_repo_snapshot,
            get_project_repo_diff,
            get_project_local_repo_diff,
            get_project_local_repo_snapshot,
            get_project_repo_sync_status,
            list_project_local_repositories,
            clone_project_repository,
            create_project_remote_branch,
            delete_project_remote_branch,
            push_project_local_repository,
            pull_project_local_repository,
            sign_project_pull_request_status,
            sign_project_pull_request_review_request,
            publish_project_pull_request_merged_status,
            merge_project_pull_request,
            open_project_terminal,
            open_project_merge_recovery_terminal,
            vingilot_agent::agent_probe,
            vingilot_agent::agent_run,
            vingilot_drop::vingilot_drop_read,
            vingilot_editor::editor_open,
            vingilot_editor::editor_probe,
            vingilot_files::read::file_read,
            vingilot_files::tree::worktree_tree,
            vingilot_harbor::harbor_install_and_start,
            vingilot_harbor::harbor_probe,
            vingilot_harbor::harbor_start,
            vingilot_harbor::harbor_status,
            vingilot_harbor::harbor_stop,
            vingilot_hooks::hook_liveness,
            vingilot_projects::projects_load,
            vingilot_projects::projects_save,
            vingilot_pty::pty_open,
            vingilot_pty::pty_write,
            vingilot_pty::pty_resize,
            vingilot_pty::pty_close,
            vingilot_pty::pty_backing,
            vingilot_pty::pty_copy_mode,
            vingilot_pty::pty_copy_mode_exit,
            vingilot_repo::repo_probe,
            vingilot_scratch::scratch_read,
            vingilot_scratch::scratch_write,
            vingilot_search::worktree_search,
            vingilot_shim::shim_install_link,
            vingilot_shim::shim_status,
            vingilot_window::window_set_dismissible,
            vingilot_worktree::worktree_list,
            vingilot_worktree::worktree_add,
            vingilot_worktree::brief::worktree_add_with_brief,
            vingilot_worktree::worktree_remove,
            vingilot_worktree::diff::worktree_diff,
            vingilot_worktree::log::worktree_log,
            vingilot_worktree::commit_patch::commit_diff,
            vingilot_worktree::status::worktree_status,
            vingilot_worktree::stat::worktree_stats,
            vingilot_worktree::prune::worktree_prune_preview,
            vingilot_worktree::prune::worktree_prune,
            search_users,
            get_presence,
            get_os_idle_seconds,
            get_default_relay_url,
            auto_connect_default_relay_enabled,
            get_legacy_workspace_storage,
            is_shared_identity,
            get_relay_ws_url,
            get_relay_http_url,
            get_media_proxy_port,
            discover_acp_auth_methods,
            discover_acp_providers,
            discover_git_bash_prerequisite,
            install_acp_runtime,
            save_custom_harness,
            delete_custom_harness,
            connect_acp_runtime,
            discover_managed_agent_prereqs,
            sign_event,
            sign_nostr_identity_binding,
            sign_out,
            decrypt_observer_event,
            build_observer_control_event,
            create_auth_event,
            nip44_encrypt_to_self,
            nip44_decrypt_from_self,
            get_channels,
            create_channel,
            ensure_starter_channels,
            open_dm,
            hide_dm,
            get_channel_details,
            get_channel_members,
            update_channel,
            set_channel_topic,
            set_channel_purpose,
            archive_channel,
            unarchive_channel,
            delete_channel,
            add_channel_members,
            remove_channel_member,
            change_channel_member_role,
            join_channel,
            leave_channel,
            get_canvas,
            set_canvas,
            get_feed,
            search_messages,
            send_channel_message,
            send_managed_agent_channel_message,
            has_managed_agent_channel_message_marker,
            get_forum_posts,
            get_forum_thread,
            get_thread_replies,
            get_channel_window,
            get_channel_messages_before,
            edit_message,
            delete_message,
            add_reaction,
            remove_reaction,
            get_event,
            show_native_notification,
            upload_media,
            pick_and_upload_media,
            pick_and_upload_image,
            upload_media_bytes,
            download_image,
            save_png_data_url,
            download_file,
            fetch_media_bytes,
            copy_image_to_clipboard,
            copy_text_to_clipboard,
            fetch_snapshot_bytes,
            relay_requires_membership,
            list_relay_members,
            get_my_relay_membership,
            add_relay_member,
            remove_relay_member,
            change_relay_member_role,
            archive_identity,
            unarchive_identity,
            list_archived_identities,
            get_relay_self,
            resolve_oa_owner,
            list_relay_agents,
            list_managed_agents,
            list_managed_agent_runtimes,
            start_managed_agent_runtime,
            stop_managed_agent_runtime,
            restart_managed_agent_runtime,
            reconcile_managed_agent_runtimes,
            put_managed_agent_runtime_lifecycle,
            create_managed_agent,
            start_managed_agent,
            stop_managed_agent,
            set_agent_managed_profiles,
            set_managed_agent_start_on_app_launch,
            set_managed_agent_auto_restart,
            delete_managed_agent,
            get_managed_agent_log,
            get_agent_models,
            discover_agent_models,
            get_agent_config_surface,
            get_runtime_file_config,
            get_baked_build_env_keys,
            get_baked_build_env,
            put_agent_session_config,
            get_global_agent_config,
            set_global_agent_config,
            mesh_start_node,
            mesh_stop_node,
            mesh_node_status,
            mesh_serving_usage,
            mesh_installed_models,
            mesh_model_catalog,
            update_managed_agent,
            discover_backend_providers,
            probe_backend_provider,
            list_personas,
            create_persona,
            update_persona,
            update_persona_and_publish,
            delete_persona,
            set_persona_active,
            set_persona_shared,
            reconcile_inbound_persona_event,
            list_channel_templates,
            create_channel_template,
            update_channel_template,
            delete_channel_template,
            duplicate_channel_template,
            list_teams,
            create_team,
            update_team,
            delete_team,
            export_agent_snapshot,
            card_mint_key_status,
            card_mint_save_openai_key,
            mint_agent_card,
            save_agent_card,
            list_agent_cards,
            load_agent_card,
            preview_agent_snapshot_import,
            confirm_agent_snapshot_import,
            encode_agent_snapshot_for_send,
            export_team_snapshot,
            encode_team_snapshot_for_send,
            preview_team_snapshot_import,
            confirm_team_snapshot_import,
            get_channel_workflows,
            get_channels_workflows,
            get_workflow,
            create_workflow,
            update_workflow,
            delete_workflow,
            get_workflow_runs,
            get_run_approvals,
            trigger_workflow,
            grant_approval,
            deny_approval,
            publish_note,
            get_contact_list,
            set_contact_list,
            get_notes_timeline,
            get_global_notes,
            get_note,
            get_note_reactions,
            get_liked_notes,
            start_huddle,
            join_huddle,
            leave_huddle,
            end_huddle,
            get_huddle_state,
            push_audio_pcm,
            reconnect_huddle_audio,
            start_stt_pipeline,
            set_huddle_transcription_enabled,
            download_voice_models,
            get_model_status,
            set_tts_enabled,
            // Dictation (vingilot/docs/plans/2026-08-13-voice.md, Task 3):
            // standalone mic-to-draft pipeline, deliberately outside
            // HuddleState — see dictation.rs's module header.
            dictation::start_dictation,
            dictation::stop_dictation,
            dictation::push_dictation_audio_pcm,
            huddle::tts_settings::get_tts_settings,
            huddle::tts_settings::list_voice_registry,
            huddle::tts_settings::set_pocket_voice,
            huddle::tts_settings::preview_pocket_voice,
            huddle::tts_settings::import_pocket_voice,
            huddle::tts_settings::delete_pocket_voice,
            speak_agent_message,
            add_agent_to_huddle,
            check_pipeline_hotstart,
            confirm_huddle_active,
            perform_sidebar_default_haptic,
            get_huddle_agent_pubkeys,
            set_voice_input_mode,
            get_voice_input_mode,
            list_audio_output_devices,
            set_audio_output_device,
            get_audio_output_device,
            start_pairing,
            confirm_pairing_sas,
            cancel_pairing,
            apply_workspace,
            validate_repos_dir,
            get_active_workspace,
            fetch_workspace_icon,
            fetch_join_policy,
            set_prevent_sleep_active,
            get_agent_memory,
            relay_reconnect_hook,
            relay_reconnect_hook_configured,
            observer_archive_default_enabled,
            agent_metric_archive_default_enabled,
            archive::archive_events,
            archive::create_save_subscription,
            archive::merge_save_subscription_kinds,
            archive::remove_save_subscription_kind,
            archive::list_save_subscriptions,
            archive::delete_save_subscription,
            archive::read_archived_events,
            archive::read_archived_observer_events_for_channel,
            archive::index_observer_channel_id,
            archive::read_unindexed_observer_rows,
            is_auto_update_supported,
            set_window_vibrancy,
            #[cfg(target_os = "macos")]
            tray_menu::clear_tray_agent_activity,
            #[cfg(target_os = "macos")]
            tray_menu::requeue_tray_actions,
            #[cfg(target_os = "macos")]
            tray_menu::take_tray_actions,
            #[cfg(target_os = "macos")]
            tray_menu::update_tray_agent_activity,
            // ── Upstream 0.5.11 merge: commands added by block/buzz across the
            // 231-commit sync. Same names/paths/cfg as upstream's lib.rs
            // generate_handler!; they resolve in lib.rs's crate-root scope like
            // every entry above. ──────────────────────────────────────────────
            terminal_runtime::terminal_attach,
            terminal_runtime::terminal_detach,
            terminal_runtime::terminal_close,
            terminal_runtime::terminal_input,
            terminal_runtime::terminal_resize,
            terminal_runtime::terminal_scroll,
            terminal_runtime::terminal_ack,
            terminal_runtime::terminal_viewport_ready,
            terminal_runtime::terminal_focus,
            #[cfg(target_os = "macos")]
            macos_notifications::take_pending_activations,
            #[cfg(target_os = "macos")]
            macos_notifications::notification_permission_state,
            #[cfg(target_os = "macos")]
            macos_notifications::request_notification_access,
            huddle::agent_voice::ensure_huddle_agent_voice_settings,
            huddle::agent_voice::set_huddle_agent_tts_enabled,
            huddle::agent_voice::set_huddle_agent_voice,
            huddle::agents::sync_agents_to_active_huddle,
            archive::get_agent_usage_series,
            close_huddle_companion,
            open_huddle_window,
            interrupt_huddle_speech,
            remove_agent_from_huddle,
            set_huddle_manual_mic_unmuted,
            read_clipboard_text,
            upload_media_bytes_raw,
            cancel_media_upload,
            fetch_link_preview_metadata,
            agent_access_owner_only,
            start_identity_recovery_pairing,
        ]
    };
}

pub(crate) use table;
